name: upside2
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy
  - scipy
  - pandas
  - matplotlib
  - seaborn
  - scikit-learn
  - h5py
  - mdanalysis
  - mdtraj
  - biopython
  - openmm
  - openmmtools
  - pymbar
  - ipykernel
  - pip
  - pip:
    - pyrosetta
    - nglview
    - plotly